// SPDX-License-Identifier: MIT
pragma solidity >=0.6.2 <0.9.0;

import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";
import {Handlers} from "./handlers/Handlers.sol";

/// @notice Contract to be used for quick testing with Foundry
contract FoundryTester is Test, Handlers {
    modifier asActor() override {
        vm.startPrank(actor);
        _;
        vm.stopPrank();
    }

    function setUp() public {
        setup();
    }

    // forge test --match-test test_sequence -vvv
    function test_sequence() public {
        // Add here call sequence to Handler's functions to reproduce failing property
    }

    // ── Violation Repros (auto-generated by Step 11) ──────────────────
    // Each test_repro_* replays a shrunk fuzzer sequence that violated a
    // property during the campaign. GL-19 has since been fixed (buyPrivate
    // reserves the public tranche) and its repro is now a regression test;
    // GL-20 remains EXPLORATORY and PASSES when the property is violated as
    // the campaign found. Run all with:
    //   FOUNDRY_PROFILE=fuzz forge test --match-contract FoundryTester -vvv

    /// GL-19 (ADV-17) regression: the campaign's shrunk sequence — one 150-unit
    /// private claim against a 200-unit escrow with 100 units public — now
    /// reverts `PublicReservationExceeded`, and the property holds.
    function test_repro_publicTrancheStarvation() public {
        setCurrentActor(0);
        try this.offering_buyPrivate(0, 150, type(uint256).max, type(uint256).max) {
            revert("GL-19: reservation should have blocked the claim");
        } catch {}

        assertEq(offering.unitsSold(), 0, "no units should have sold");
        property_publicTrancheStaysFillable();
    }

    /// GL-20: sweeping a failed raise into a treasury that already holds units
    /// collapses the cap table to a single holder. On real 0xSplits SplitMain a
    /// one-account split is rejected (`_validSplit` needs >= 2), so all future
    /// revenue is permanently stuck in `payoutSplit` — value locked, not lost.
    function test_repro_capTableCollapse() public {
        setCurrentActor(0);
        offering_roundTrip_buyFailRefund(); // buy 1 -> markFailed -> refund; escrow holds all 200 again

        // Redirect the treasury onto the founder (actors[2], 800 units) and sweep:
        // the 200 escrowed units join the 800, leaving 1000 units at one address.
        vm.prank(offering.owner());
        offering.setTreasury(actors[2]);
        offering.sweepFailedUnits();

        assertEq(token.balanceOf(actors[2], TOKEN_ID), 1000, "founder should hold the entire cap table");
        try this.property_capTableKeepsTwoHolders() {
            revert("GL-20 should be violated: cap table collapsed to one holder");
        } catch {}
    }
}
