// SPDX-License-Identifier: MIT
pragma solidity >=0.6.2 <0.9.0;

import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";
import {Handlers} from "./handlers/Handlers.sol";

/// @notice Contract to be used for quick testing with Foundry
contract FoundryTester is Test, Handlers {
    modifier asActor() override {
        vm.startPrank(actor);
        _;
        vm.stopPrank();
    }

    function setUp() public {
        setup();
    }

    // forge test --match-test test_sequence -vvv
    function test_sequence() public {
        // Add here call sequence to Handler's functions to reproduce failing property
    }

    // ── Violation Repros (auto-generated by Step 11) ──────────────────
    // Each test_repro_* replays a shrunk fuzzer sequence that violated a
    // property. Both violated properties are EXPLORATORY (design observations
    // flagged for human review, not confirmed protocol bugs). Each test PASSES
    // when the property is violated as the campaign found. Run all with:
    //   FOUNDRY_PROFILE=fuzz forge test --match-contract FoundryTester -vvv

    /// GL-19 (ADV-17): one private claim can drain units the public tranche
    /// still advertises as available. `buyPrivate` is bounded only by
    /// `remainingUnits()`, never by `publicUnits - publicUnitsSold`, so a single
    /// voucher holder buys out the whole escrow and every later `buyPublic`
    /// reverts `InsufficientSupply` while the cap still shows 100 units free.
    function test_repro_publicTrancheStarvation() public {
        setCurrentActor(0);
        // Buy 150 of the 200 escrowed units through the private tranche. Nothing
        // caps a private claim against the public reservation, so this leaves
        // only 50 sellable while publicUnits still advertises 100.
        offering_buyPrivate(0, 150, type(uint256).max, type(uint256).max);

        uint256 advertised = offering.publicUnits() - offering.publicUnitsSold();
        assertLt(offering.remainingUnits(), advertised, "public tranche should now be unfillable");
        try this.property_publicTrancheStaysFillable() {
            revert("GL-19 should be violated: public tranche starved");
        } catch {}
    }

    /// GL-20: sweeping a failed raise into a treasury that already holds units
    /// collapses the cap table to a single holder. On real 0xSplits SplitMain a
    /// one-account split is rejected (`_validSplit` needs >= 2), so all future
    /// revenue is permanently stuck in `payoutSplit` — value locked, not lost.
    function test_repro_capTableCollapse() public {
        setCurrentActor(0);
        offering_roundTrip_buyFailRefund(); // buy 1 -> markFailed -> refund; escrow holds all 200 again

        // Redirect the treasury onto the founder (actors[2], 800 units) and sweep:
        // the 200 escrowed units join the 800, leaving 1000 units at one address.
        vm.prank(offering.owner());
        offering.setTreasury(actors[2]);
        offering.sweepFailedUnits();

        assertEq(token.balanceOf(actors[2], TOKEN_ID), 1000, "founder should hold the entire cap table");
        try this.property_capTableKeepsTwoHolders() {
            revert("GL-20 should be violated: cap table collapsed to one holder");
        } catch {}
    }
}
