// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {BaseTest} from "./Base.t.sol";
import {Offering} from "../src/Offering.sol";
import {PactToken} from "../src/PactToken.sol";

// Pins the JS ↔ Solidity voucher boundary: the fixture is generated by
// scripts/generate-voucher-fixture.ts from src/lib/voucher.ts, and the
// real verifier must accept its signatures end to end.
contract GoldenVectorTest is BaseTest {
    function testGoldenVoucherVector() public {
        string memory json = vm.readFile("../tests/fixtures/voucher-golden.json");
        vm.chainId(vm.parseJsonUint(json, ".chainId"));

        address deployer = vm.parseJsonAddress(json, ".deployer");
        address owner = vm.parseJsonAddress(json, ".owner");
        address claimBuyer = vm.parseJsonAddress(json, ".buyer");

        vm.prank(deployer); // fresh EOA, nonce 0 — the fixture precomputes the CREATE address
        Offering golden = new Offering(100e6, uint64(block.timestamp + 7 days), 1e6, 1000, 100, owner, owner);
        assertEq(address(golden), vm.parseJsonAddress(json, ".offering"), "fixture address drift");

        address[] memory goldenHolders = new address[](1);
        goldenHolders[0] = holder;
        uint32[] memory goldenAllocations = new uint32[](1);
        goldenAllocations[0] = 800;
        PactToken goldenToken =
            new PactToken(address(splitMain), "Golden", goldenHolders, goldenAllocations, address(golden), 200);
        vm.prank(deployer);
        golden.initialize(address(goldenToken));

        Offering.Voucher memory voucher = Offering.Voucher({
            allocationId: vm.parseJsonBytes32(json, ".voucher.allocationId"),
            buyerName: vm.parseJsonString(json, ".voucher.buyerName"),
            amountCapUsdc: vm.parseJsonUint(json, ".voucher.amountCapUsdc"),
            linkKey: vm.parseJsonAddress(json, ".linkKey")
        });
        bytes memory ownerSig = vm.parseJsonBytes(json, ".ownerSig");
        bytes memory claimSig = vm.parseJsonBytes(json, ".claimSig");

        // The Solidity digests reproduce the JS signatures bit for bit.
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(vm.parseJsonUint(json, ".ownerKey"), golden.voucherDigest(voucher));
        assertEq(abi.encodePacked(r, s, v), ownerSig, "owner sig drift");

        // And the real verifier accepts the fixture end to end.
        usdc.mint(claimBuyer, 1_000e6);
        vm.startPrank(claimBuyer);
        usdc.approve(address(golden), type(uint256).max);
        uint256 cost = golden.buyPrivate(voucher, ownerSig, claimSig, 100, type(uint256).max);
        vm.stopPrank();
        assertGt(cost, 0, "golden cost");
        assertEq(goldenToken.balanceOf(claimBuyer, 0), 100, "golden claim");
    }
}
