import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedDir = path.join(root, 'src', 'generated');
const outputPath = path.join(generatedDir, 'offering-contracts.ts');

function readArtifact(contractPath: string, name: string) {
  const artifact = JSON.parse(fs.readFileSync(path.join(root, 'contracts', 'out', contractPath, name + '.json'), 'utf8'));
  return {
    abi: artifact.abi as unknown[],
    bytecode: artifact.bytecode.object as string,
  };
}

// The pinned deployment (address + scan lower bound) survives regeneration.
function existingConstant(name: string, fallback: string): string {
  // Fall back to the pre-TypeScript filename so the pin survives the .js → .ts move.
  const source = [outputPath, outputPath.replace(/\.ts$/, '.js')].find(p => fs.existsSync(p));
  if (!source) return fallback;
  const text = fs.readFileSync(source, 'utf8');
  const match = text.match(new RegExp(name + " = '?([^';\\n]*)'?"));
  return match ? match[1] : fallback;
}

const factory = readArtifact('OfferingFactory.sol', 'OfferingFactory');
const offering = readArtifact('Offering.sol', 'Offering');
const pactToken = readArtifact('PactToken.sol', 'PactToken');

fs.mkdirSync(generatedDir, { recursive: true });
fs.writeFileSync(outputPath, `// Generated by scripts/export-contracts.ts. Do not edit by hand.
export const OFFERING_FACTORY_ADDRESS = '${existingConstant('OFFERING_FACTORY_ADDRESS', '')}';
// Lower bound for every OfferingCreated event scan.
export const OFFERING_FACTORY_DEPLOY_BLOCK = ${Number(existingConstant('OFFERING_FACTORY_DEPLOY_BLOCK', '0')) || 0};
export const OFFERING_FACTORY_ABI = ${JSON.stringify(factory.abi, null, 2)} as const;
export const OFFERING_FACTORY_BYTECODE = '${factory.bytecode}';
export const OFFERING_ABI = ${JSON.stringify(offering.abi, null, 2)} as const;
export const PACT_TOKEN_ABI = ${JSON.stringify(pactToken.abi, null, 2)} as const;
`);

console.log('Wrote src/generated/offering-contracts.ts');
